export type ColorsT = {
  // primary
  primary_100: string;
  primary_75: string;
  primary_50: string;
  primary_25: string;
  primary_12: string;
  // secondary
  secondary_100: string;
  secondary_75: string;
  secondary_50: string;
  secondary_25: string;
  secondary_12: string;
  // black
  black_100: string;
  black_75: string;
  black_50: string;
  black_25: string;
  black_12: string;
  // neotural
  neo: string;
  neo_2: string;
  white: string;
  // green
  green_1: string;
  green_2: string;
  // red
  red_1: string;
  red_2: string;
  // violet
  violet_1: string;
  violet_2: string;
};
